//
//  AccountInteractor.swift
//  BookPlace
//
//  Created by Artem Lyksa on 3/9/17.
//  Copyright (c) 2017 Artem Lyksa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol AccountInteractorInput
{
  func doSomething(request: Account.Something.Request)
}

protocol AccountInteractorOutput
{
  func presentSomething(response: Account.Something.Response)
}

class AccountInteractor: AccountInteractorInput
{
  var output: AccountInteractorOutput!
  var worker: AccountWorker!
  
  // MARK: - Business logic
  
  func doSomething(request: Account.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = AccountWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = Account.Something.Response()
    output.presentSomething(response: response)
  }
}
