//
//  AccountViewController.swift
//  BookPlace
//
//  Created by Artem Lyksa on 3/9/17.
//  Copyright (c) 2017 Artem Lyksa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol AccountViewControllerInput
{
    func displaySomething(viewModel: Account.Something.ViewModel)
}

protocol AccountViewControllerOutput
{
    func doSomething(request: Account.Something.Request)
}

class AccountViewController: UIViewController, AccountViewControllerInput
{
    var output: AccountViewControllerOutput!
    var router: AccountRouter!
    
    @IBOutlet weak var userImageView: UIImageView!
    @IBOutlet weak var userFullNameLabel: UILabel!
    
    // MARK: - Object lifecycle
    
    override func awakeFromNib()
    {
        super.awakeFromNib()
        AccountConfigurator.sharedInstance.configure(viewController: self)
    }
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        setUpUIElements()
    }
    
    func setUpUIElements()
    {
        userFullNameLabel.text = User.sharedInstance().name
        if let image = User.sharedInstance().image {
            userImageView.image = image
        }
    }
        
    func displaySomething(viewModel: Account.Something.ViewModel)
    {
        // NOTE: Display the result from the Presenter
        
        // nameTextField.text = viewModel.name
    }
    @IBAction func logOutButtonTapped(_ sender: UIButton) {
        User.destroy()
        router.navigateToSignIn()
    }
}
