//
//  BookListInteractor.swift
//  BookPlace
//
//  Created by Artem Lyksa on 3/8/17.
//  Copyright (c) 2017 Artem Lyksa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol BookListInteractorInput
{
    func getBookList(request: BookList.GetBookList.Request)
    func getImage(request: BookList.GetBookImage.Request)
    func stopLoadingImage(request: BookList.StopLoadingImageProcess.Request)
    func removeBookList(request:BookList.RemoveBookList.Request)
}

protocol BookListInteractorOutput
{
    func presentBookList(response: BookList.GetBookList.Response)
    func presentBookImage(response:BookList.GetBookImage.Response)
}

class BookListInteractor: BookListInteractorInput
{
    var output: BookListInteractorOutput!
    let queue = OperationQueue()
    var worker: BookListWorker!
    
    // MARK: - Business logic
    func getBookList(request: BookList.GetBookList.Request)
    {
        SearchService.sharedInstace.getBookListWithString(searchString: request.searchString) { (json, error) in
            guard let result = json else { return }
            self.createBooksFromJson(json: result)
        }
    }
    
    func createBooksFromJson(json: [String:AnyObject])
    {
        var books:[BookList.GetBookList.Response.BookData] = []
        if let items = json["items"] as? [[String:AnyObject]] {
            for item in items {
                guard let volumeInfo = item["volumeInfo"] as? [String : AnyObject] else { continue }
                guard let title = volumeInfo["title"] as? String,
                    let authors = volumeInfo["authors"] as? [String],
                    let description = volumeInfo["description"] as? String else { continue }
                
                var imageURL: URL?
                if let imageLinks = volumeInfo["imageLinks"] as? [String : AnyObject] {
                    if let thumbnail = imageLinks["thumbnail"] as? String {
                        imageURL = URL.init(string: thumbnail)
                    }
                    if let smallThumbnail = imageLinks["smallThumbnail"] as? String {
                        imageURL = URL.init(string: smallThumbnail)
                    }
                    if let previewLink = imageLinks["previewLink"] as? String {
                        imageURL = URL.init(string: previewLink)
                    }
                }
                let bookData = BookList.GetBookList.Response.BookData(bookName: title, authors: authors, description: description, imageURL: imageURL)
                books.append(bookData)
            }
        }
        output.presentBookList(response: BookList.GetBookList.Response(books: books))
    }


    func getImage(request: BookList.GetBookImage.Request) {
        guard let imageURL = request.book.imageURL else { return }
        let imgOperation = BlockOperation.init(block: {
            do {
                let imageData = try Data.init(contentsOf: imageURL)
                request.book.image = UIImage.init(data: imageData)
                self.output.presentBookImage(response: BookList.GetBookImage.Response(book: request.book))
            } catch {
                print("Data is nil")
            }
        })
        queue.qualityOfService = .background
        queue.addOperation(imgOperation)
    }
    
    func stopLoadingImage(request: BookList.StopLoadingImageProcess.Request) {
        queue.cancelAllOperations()
    }
    
    func removeBookList(request: BookList.RemoveBookList.Request) {
        queue.cancelAllOperations()
        output.presentBookList(response: BookList.GetBookList.Response(books: nil))
    }
}
