//
//  BookListModels.swift
//  BookPlace
//
//  Created by Artem Lyksa on 3/8/17.
//  Copyright (c) 2017 Artem Lyksa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct BookList
{
    struct GetBookList
    {
        struct Request
        {
            var searchString: String!
        }
        struct Response
        {
            struct BookData {
                var bookName: String!
                var authors: [String]!
                var description: String!
                var imageURL: URL?
            }
            var books: [BookData]?
        }
        struct ViewModel
        {
            var bookList: [Book]!
        }
    }
    
    
    struct GetBookImage
    {
        struct Request
        {
            var book: Book!
        }
        struct Response
        {
            var book: Book!
        }
        struct ViewModel
        {
            var book: Book!
        }
    }
    
    struct StopLoadingImageProcess
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    
    struct RemoveBookList
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    
    
  struct Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
