//
//  BookBacketInteractor.swift
//  BookPlace
//
//  Created by Artem Lyksa on 3/9/17.
//  Copyright (c) 2017 Artem Lyksa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol BookBacketInteractorInput
{
  func doSomething(request: BookBacket.Something.Request)
}

protocol BookBacketInteractorOutput
{
  func presentSomething(response: BookBacket.Something.Response)
}

class BookBacketInteractor: BookBacketInteractorInput
{
  var output: BookBacketInteractorOutput!
  var worker: BookBacketWorker!
  
  // MARK: - Business logic
  
  func doSomething(request: BookBacket.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = BookBacketWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = BookBacket.Something.Response()
    output.presentSomething(response: response)
  }
}
