//
//  BookBasketInteractor.swift
//  BookPlace
//
//  Created by Artem Lyksa on 3/9/17.
//  Copyright (c) 2017 Artem Lyksa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol BookBasketInteractorInput
{
  func doSomething(request: BookBasket.Something.Request)
}

protocol BookBasketInteractorOutput
{
  func presentSomething(response: BookBasket.Something.Response)
}

class BookBasketInteractor: BookBasketInteractorInput
{
  var output: BookBasketInteractorOutput!
  var worker: BookBasketWorker!
  
  // MARK: - Business logic
  
  func doSomething(request: BookBasket.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = BookBasketWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = BookBasket.Something.Response()
    output.presentSomething(response: response)
  }
}
