//
//  BookDetailsInteractor.swift
//  BookPlace
//
//  Created by Artem Lyksa on 3/9/17.
//  Copyright (c) 2017 Artem Lyksa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol BookDetailsInteractorInput
{
    func createRightBarButton(request:BookDetails.CreateRightBarButton.Request)
    func addBookToBasket(request:BookDetails.AddBookToBasket.Request)
    func removeBookFormBasket(request:BookDetails.RemoveBookFromBasket.Request)

}

protocol BookDetailsInteractorOutput
{
    func presentRightBarButton(request:BookDetails.CreateRightBarButton.Request)
    func addBookToBasket(request:BookDetails.AddBookToBasket.Response)
    func removeBookFormBasket(request:BookDetails.RemoveBookFromBasket.Response)
}

class BookDetailsInteractor: BookDetailsInteractorInput
{
  var output: BookDetailsInteractorOutput!
  var worker: BookDetailsWorker!
  
    func createRightBarButton(request: BookDetails.CreateRightBarButton.Request) {
        output.presentRightBarButton(request: request)
    }
    
    func addBookToBasket(request: BookDetails.AddBookToBasket.Request) {
        output.addBookToBasket(request: BookDetails.AddBookToBasket.Response())
    }
    
    func removeBookFormBasket(request: BookDetails.RemoveBookFromBasket.Request) {
        output.removeBookFormBasket(request: BookDetails.RemoveBookFromBasket.Response())
    }
  // MARK: - Business logic

}
