//
//  BookDetailsModels.swift
//  BookPlace
//
//  Created by Artem Lyksa on 3/9/17.
//  Copyright (c) 2017 Artem Lyksa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct BookDetails
{
    struct CreateRightBarButton
    {
        struct Request
        {
            var title: String!
        }
        struct Response
        {
        }
        struct ViewModel
        {
            var rightBarButtonItem: UIBarButtonItem!
        }
    }
    
    struct AddBookToBasket
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    struct RemoveBookFromBasket
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    
  struct Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
