//
//  BookListModels.swift
//  BookPlace
//
//  Created by Artem Lyksa on 3/8/17.
//  Copyright (c) 2017 Artem Lyksa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct BookList
{
    struct GetBookList
    {
        struct Request
        {
            var searchString: String!
        }
        struct Response
        {
            var bookList: [Book]?
        }
        struct ViewModel
        {
            var bookName: String!
            var authors: String!
            var image: UIImage!
            var imageURL: URL?
        }
    }
    
    
    struct GetBookImage
    {
        struct Request
        {
            var imageURL: URL?
            var indexPath: IndexPath!
        }
        struct Response
        {
            var imageData: Data!
            var indexPath: IndexPath!
        }
        struct ViewModel
        {
            var image: UIImage!
            var indexPath: IndexPath!
        }
    }
    
    struct StopLoadingImageProcess
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    
    
  struct Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
