//
//  BookBasketViewController.swift
//  BookPlace
//
//  Created by Artem Lyksa on 3/9/17.
//  Copyright (c) 2017 Artem Lyksa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol BookBasketViewControllerInput
{
}

protocol BookBasketViewControllerOutput
{
    func doSomething(request: BookBasket.Something.Request)
}

class BookBasketViewController: UIViewController, BookBasketViewControllerInput
{
    @IBOutlet weak var tableView: UITableView!
    var output: BookBasketViewControllerOutput!
    var router: BookBasketRouter!
    var dataSource: [Book] = []
    var heights = [IndexPath:CGFloat]()

    // MARK: - Object lifecycle
    
    override func awakeFromNib()
    {
        super.awakeFromNib()
        BookBasketConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: - View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        tableView.tableFooterView = UIView.init()
        tableView.rowHeight = UITableViewAutomaticDimension
        tableView.estimatedRowHeight = 100.0
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        dataSource = User.sharedInstance().books
        tableView.reloadData()
    }
}

extension BookBasketViewController: UITableViewDelegate, UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return dataSource.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let bookCell = tableView.dequeueReusableCell(withIdentifier: "bookCell", for: indexPath) as! BookTableViewCell
        let book = dataSource[indexPath.row]
        bookCell.bookNameLabel.text = book.name
        bookCell.bookAuthorLabel.text = book.authors
        if let image = book.image {
            bookCell.bookImageView.image = image
        }
        return bookCell
    }
    
    func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        if (cell.frame.size.height > 0) {
            heights[indexPath] = cell.frame.size.height
        }
    }
    
    func tableView(_ tableView: UITableView, estimatedHeightForRowAt indexPath: IndexPath) -> CGFloat {
        if let height = heights[indexPath], height > 10.0 {
            return height
        } else {
            return 100.0
        }
    }
    
    func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
        return 0.0
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        router.navigateToBookDetailsScene(fromIndexPath: indexPath)
    }
}
