//
//  BookListConfigurator.swift
//  BookPlace
//
//  Created by Artem Lyksa on 3/8/17.
//  Copyright (c) 2017 Artem Lyksa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension BookListViewController: BookListPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension BookListInteractor: BookListViewControllerOutput
{
}

extension BookListPresenter: BookListInteractorOutput
{
}

class BookListConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = BookListConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: BookListViewController)
  {
    let router = BookListRouter()
    router.viewController = viewController
    
    let presenter = BookListPresenter()
    presenter.output = viewController
    
    let interactor = BookListInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
