//
//  BookBacketConfigurator.swift
//  BookPlace
//
//  Created by Artem Lyksa on 3/9/17.
//  Copyright (c) 2017 Artem Lyksa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension BookBacketViewController: BookBacketPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension BookBacketInteractor: BookBacketViewControllerOutput
{
}

extension BookBacketPresenter: BookBacketInteractorOutput
{
}

class BookBacketConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = BookBacketConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: BookBacketViewController)
  {
    let router = BookBacketRouter()
    router.viewController = viewController
    
    let presenter = BookBacketPresenter()
    presenter.output = viewController
    
    let interactor = BookBacketInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
