//
//  SignInViewController.swift
//  BookPlace
//
//  Created by Artem Lyksa on 3/8/17.
//  Copyright (c) 2017 Artem Lyksa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import GoogleSignIn

protocol SignInViewControllerInput
{
    func displayUserInfo(viewModel: SignIn.Authenticate.ViewModel)
}

protocol SignInViewControllerOutput
{
    func signInWithFacebook(request: SignIn.Authenticate.Request)
    func signInWithGoogle(request: SignIn.Authenticate.Request)
    func getImageForUser(requset: SignIn.GetImage.Request)
}

class SignInViewController: UIViewController, SignInViewControllerInput
{
    var output: SignInViewControllerOutput!
    var router: SignInRouter!
    
    // MARK: - Object lifecycle
    
    override func awakeFromNib()
    {
        super.awakeFromNib()
        SignInConfigurator.sharedInstance.configure(viewController: self)
        GIDSignIn.sharedInstance().uiDelegate = self
    }
    
    // MARK: - View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
    }
    

    @IBAction func loginWithFacebookButtonTapped(_ sender: UIButton) {
        output.signInWithFacebook(request: SignIn.Authenticate.Request())
    }
    
    @IBAction func loginWithGoogleButtonTapped(_ sender: UIButton) {
        output.signInWithGoogle(request: SignIn.Authenticate.Request())
    }
    
    func displayUserInfo(viewModel: SignIn.Authenticate.ViewModel) {
        output.getImageForUser(requset: SignIn.GetImage.Request(imageURL: viewModel.user.imageURL))
        router.navigateToTabBarScene()
    }
}


extension SignInViewController: GIDSignInUIDelegate {
    func sign(_ signIn: GIDSignIn!, present viewController: UIViewController!) {
        self.present(viewController, animated: true, completion: nil)
    }
}
