//
//  SignInInteractor.swift
//  BookPlace
//
//  Created by Artem Lyksa on 3/8/17.
//  Copyright (c) 2017 Artem Lyksa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import GoogleSignIn

protocol SignInInteractorInput
{
    func signInWithFacebook(request: SignIn.Authenticate.Request)
    func signInWithGoogle(request: SignIn.Authenticate.Request)
}

protocol SignInInteractorOutput
{
    func presentUserInfo(response: SignIn.Authenticate.Response)
}

class SignInInteractor: NSObject, SignInInteractorInput
{
    var output: SignInInteractorOutput!
    var worker: SignInWorker!
    
    // MARK: - Business logic
    func signInWithFacebook(request: SignIn.Authenticate.Request) {
        worker = SignInWorker()
        worker.signInWithFacebook { (user) in
            let response = SignIn.Authenticate.Response(user: user)
            self.output.presentUserInfo(response: response)
        }
    }
    
    func signInWithGoogle(request: SignIn.Authenticate.Request) {
        GIDSignIn.sharedInstance().delegate = self
        worker = SignInWorker()
        worker.signInWithGoogle()
    }
}

extension SignInInteractor: GIDSignInDelegate {
    
    func sign(_ signIn: GIDSignIn!, didSignInFor user: GIDGoogleUser!, withError error: Error!) {
        if error == nil {
            let user = User(name: signIn.currentUser.profile.name, email: signIn.currentUser.profile.email)
            UserDefaults.standard.set(signIn.currentUser.authentication.accessToken, forKey: "token")
            let response = SignIn.Authenticate.Response(user: user)
            self.output.presentUserInfo(response: response)
        } else {
         print(error)
        }

    }
    
    func sign(_ signIn: GIDSignIn!, didDisconnectWith user: GIDGoogleUser!, withError error: Error!) {
        print(error)
    }
}

