//
//  SignInModels.swift
//  BookPlace
//
//  Created by Artem Lyksa on 3/8/17.
//  Copyright (c) 2017 Artem Lyksa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct SignIn
{
    struct Authenticate {
        struct Request
        {
        }
        struct Response
        {
            var email: String!
            var name:  String!
            
        }
        struct ViewModel
        {
            var user: User
        }
    }
}
