//
//  SignInPresenter.swift
//  BookPlace
//
//  Created by Artem Lyksa on 3/8/17.
//  Copyright (c) 2017 Artem Lyksa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SignInPresenterInput
{
    
}

protocol SignInPresenterOutput: class
{
    func displayUserInfo(viewModel: SignIn.Authenticate.ViewModel)
}

class SignInPresenter: SignInPresenterInput
{
    weak var output: SignInPresenterOutput!
    
    // MARK: - Presentation logic
    func presentUserInfo(response: SignIn.Authenticate.Response) {
        let model = SignIn.Authenticate.ViewModel(email: response.user.email, name: response.user.name)
        output.displayUserInfo(viewModel: model)
    }
}
